spring:
  datasource:
        url: jdbc:mysql://localhost:3306/gmall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application: manage-service    #dubbo的服务名称
    registry:
      address: 192.168.190.136:2181   #zookeeper注册中心的地址
      protocol: zookeeper #zookeeper通讯协议名称
    protocol:
      name: dubbo #dubbo通讯协议名称
    base-package: com.gmall.manage #dubbo服务扫描路径
server:
  port: 8071

logging:
 level:
   root: info

